trigger:
  paths:
    include:
      - environments/prod/*


variables:
 - group: terraform-secrets

 
stages:
  - stage: Initialize
    displayName: Initialize
    jobs:
      - job: InitializeProdEnv
        displayName: "Initialize Prod environment"
        pool:
            name: noteapp-agents
        steps:
          - template: templates/template-steps.yaml
            parameters:
              environment: prod


  - stage: Deploy
    displayName: Deploy
    jobs:
      - deployment: TerraformApplyProd
        displayName: "Deploy to prod env post approval"
        environment: terraform-prod-env
        pool: 
          name: noteapp-agents
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                   cd $(Build.SourcesDirectory)/environments/prod/                
                   terraform apply -auto-approve tfplan
                  displayName: 'Terraform Apply'
            


