# azure-pipelines.yml

# trigger:
#   branches:
#     include:
#       - main

parameters:
  - name: services
    type: object
    default:
      - name: storage
        path: terraform/environments/dev/storage
      - name: vm
        path: terraform/environments/dev/vm
      - name: network
        path: terraform/environments/dev/network

stages:
  - stage: TerraformDeployment
    displayName: Terraform CI/CD
    jobs:
      - ${{ each service in parameters.services }}:
        - job: Deploy_${{ service.name }}
          displayName: Deploy ${{ service.name }}
          condition: >
            and(
              eq(variables['Build.SourceBranch'], 'refs/heads/main'),
              changes['${{ service.path }}/**']
            )
          pool:
            vmImage: ubuntu-latest
          steps:
            - script: |
                cd ${{ service.path }}
                terraform init -input=false
              displayName: 'Terraform Init'

            - script: |
                cd ${{ service.path }}
                terraform plan -out=tfplan
              displayName: 'Terraform Plan'

            - script: |
                cd ${{ service.path }}
                terraform apply -auto-approve tfplan
              displayName: 'Terraform Apply'
